# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up age
      run: | 
        sudo apt update
        sudo apt install -y age

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Set up fake-gcs-server
      run: |
        export STORAGE_EMULATOR_HOST="localhost:4443"
        docker pull fsouza/fake-gcs-server
        docker run -d --name fake-gcs-server -p 4443:4443 fsouza/fake-gcs-server

    - name: Test
      run: | 
        go test -v ./cmd

    - name: Bump version, Build, and Push
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

        # Extract current version from cmd/root.go
        CURRENT_VERSION=$(grep 'Version:' cmd/root.go | awk -F'"' '{print $2}')
        echo "Current Version: $CURRENT_VERSION"

        # Increment patch version (e.g., 0.0.1 -> 0.0.2)
        IFS='.' read -r -a parts <<< "$CURRENT_VERSION"
        NEW_PATCH=$((parts[2] + 1))
        NEW_VERSION="${parts[0]}.${parts[1]}.$NEW_PATCH"
        echo "New Version: $NEW_VERSION"

        # Update version in cmd/root.go
        sed -i "s/Version: \"$CURRENT_VERSION\"/Version: \"$NEW_VERSION\"/" cmd/root.go

        # Update version in README.md
        sed -i "s/go-crypt-sync v$CURRENT_VERSION/go-crypt-sync v$NEW_VERSION/" README.md

        # Build the new binary
        go build -v -o bin/go-crypt-sync .

        # Commit and push changes
        # We use [skip ci] to prevent an infinite loop of workflows
        git add cmd/root.go bin/go-crypt-sync README.md
        git commit -m "Bump version to $NEW_VERSION [skip ci]"
        git push
